sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - development

# matrix:
#   allow_failures:
#     - haxe: development

install:
  - haxelib install travix
  - haxelib install hmm
  - yes | haxelib run hmm install
  - haxelib dev abe .
  - npm install
  # - haxelib run travix install

script:
  - haxelib run travix node
